name: GitHub Pages

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      - name: Build
        run: |
          python -c "import json; f = open('bin.rcn.json'); bin = json.loads(f.read()); f.close(); f = open('gh-pages/index.html'); content = f.read(); f.close(); f = open('gh-pages/index.html', 'w+'); f.write(content.replace('$RCN_STATIC_BIN', json.dumps(bin))); f.close();"
          git lfs track gh-pages/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: gh-pages
